# Generated by Django 3.0.2 on 2020-07-17 20:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='curriculum',
            field=ckeditor.fields.RichTextField(default='texto'),
        ),
    ]
